# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 17
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Install pack CLI via the official buildpack Action
      uses: buildpacks/github-actions/setup-pack@v4.8.1

    - name: Build app with pack CLI & publish to GitHub Container Registry
      run: |
          pack build ghcr.io/crowin/spb-marketplace:latest \
              --builder paketobuildpacks/builder:base \
              --path . \
              --env "BP_OCI_SOURCE=https://github.com/crowin/spb-marketplace" \
              --env "BP_JVM_VERSION=17" \
              --cache-image ghcr.io/jonashackt/spb-marketplace-cache-image:latest \
              --publish
